name: Cal PR Review

on:
  workflow_dispatch:
    inputs:
      config:
        type: string
        description: "config for reviewer"
        required: true
      head:
        type: string
        description: "head commit sha"
        required: true
      base:
        type: string
        description: "base commit sha"
        required: false
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.head }}

      - name: Run reviewer
        uses: addnab/docker-run-action@v3
        with:
          image: callstackai/cal:latest
          options: -v ${{ github.workspace }}:/code
          run: |
            /reviewer --dir /code  --id ${{ github.run_id }} --token ${{ github.token }} --config "${{ inputs.config }}"
